PRODUCT_VERSION_MAJOR = 21
PRODUCT_VERSION_MINOR = 0

KURONEKO_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)

# Set KURONEKO_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef KURONEKO_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "KURONEKO_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^KNXD_||g')
        KURONEKO_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(KNXD_BUILDTYPE)),)
    KNXD_BUILDTYPE := UNOFFICIAL
    KURONEKO_EXTRAVERSION :=
endif

ifeq ($(KURONEKO_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        KURONEKO_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

KURONEKO_VERSION_SUFFIX := $(KURONEKO_BUILD_DATE)-$(KURONEKO_BUILDTYPE)$(KURONEKO_EXTRAVERSION)-$(KURONEKO_BUILD)

# Internal version
KURONEKO_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(KURONEKO_VERSION_SUFFIX)

# Display version
KURONEKO_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(KURONEKO_VERSION_SUFFIX)
